kind: Service
apiVersion: v1
metadata:
  name:  demosevice
spec:
  type: NodePort
  selector:
    myvalue:  demo  # apply this service to any pod which has this specified label
  ports:
  - port:  80
    targetPort:  80
    nodePort: 30008

