apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebspv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentvolumeclaimpolicy: Recycle
  awsElasticBlockstore:
    volumeid: vol-046b6454fd94c1180
    fstype: ext4




    