apiVersion: batch/v1
kind: Job
metadata:
  name:  throw-dice-job
spec:
  backoffLimit: 15
  template:
    spec:
      containers:
      - name: math-add
        image: kodekloud/throw-dice
      restartPolicy: Never 
