apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:        #used to tag pods or resources in the kubernetes 
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: voting-app
    image: dockersamples/examplevotingapp_vote
    ports:
    - containerPort: 80
