apiVersion: apps/v1
kind: Deployment
metadata:
  name: Enter deployment name
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-container
        image: nginx
  selector:
    matchLabels:
      type: front-end